#Essa deve ser a lista mais extensa porque é a mais utilizada
from Auxiliares.aux_functions import contador

pessoas_comum = [
#Política
    'Lula',
    'Dilma',
    'Ciro Gomes',
    'Marina Silva',
    'Eduardo Jorge',
    'Boulos (50)',
    'Haddad',
    'Tábata Amaral',
    'Bolsonaro',
    'Mourão',
    'Paulo Guedes',
    'Moro',
    'Daciolo',
    'Temer',
    'Dória',
    'FHC',
    'Trump',
    'Joe Biden',
#Artistas
    'Mano Brown',
    'Baco Exu do Blues',
    'Humberto Gessinger',
    'Rita Lee',
    'Anitta',
    'Pabllo Vittar',
    'Gloria Groove',
    'Sandy',
    'Tiago Iorc',
    'Gilberto Gil',
    'Caetano Veloso',
    'Chico Buarque',
    'Roberto Carlos',
    'Perícles',
    'Lulu Santos',
    'Michel Teló',
    'Alceu Valença',
    'Ivete Sangalo',
    'Gusttavo Lima',
    'Cláudia Leitte',
    'MC Kevin',
    'MC Carol',
    'MC Rebecca',
    'Jojo Toddynho',
    'Luan Santana',
    'Manu Gavassi',
    'Supla',
    'Dilsinho',
    'Wesley Safadão',
    'Alok',
#Artistas Internacionais
    'Lady Gaga',
    'SZA',
    'Rihanna',
    'Ariana Grande',
    'Nicki Minaj',
    'Billie Eilish',
    'Camila Cabello',
    'Shawn Mendes',
    'Harry Styles',
    'The Weeknd',
    'Drake',
    'Taylor Swift',
    'Kayne West',
#Personalidades
    'Átila',
    'Whinderson Nunes',
    'Fábio Porchat',
    'Marcelo Adnet',
    'Tatá Werneck',
    'Dani Calabresa',
    'Gregório Duvivier',
    'Felipe Neto',
    'Felipe Castanhari',
    'Kefera',
    'Luciano Huck',
    'Pedro Bial',
    'Xuxa',
    'Didi',
    'Fátima Bernardes',
    'Faustão',
    'Galvão Bueno',
    'Willian Bonner', 
    'Glória Maria',
    'Ana Maria Braga',
    'Silvio Santos',
    'Rodrigo Hilbert',
#Esporte
    'Gabigol',
    'Ronaldinho Gaucho',
    'Ribamar',
    'Richarlison',
    'Arrascaeta',
    'Everton Cebolinha',
    'Firmino',
    'Neymar',
    'Pelé',
    'Tite',
    'Romário',
#Atores
    'Cláudia Raia',
    'Bruna Marquezine',
    'Isis Valverde',
    'Marina Rui Barbosa',
    'Juliana Paes',
    'Taís Araujo',
    'Antônio Fagundes',
    'Tony Ramos',
    'Suzana Vieira',
    'Bruno Gagliasso',
    'Lázaro Ramos',
    'Babu Santana'
]

pessoas_raro = [
    'você',
    'sua mãe',
    'seu pai',
    'sua ex',
    'seu ex',
    'uma loiro odonto',
    'um hetero top',
    'Chico Barney',
    'Harry Potter',
    'Olavo de Caralho',
    'uma das meninas do Anavitória (sei lá o nome delas kkkk)',
    'pai do Cid Não Salvo',
    'Selena Gomes',
    'Ednaldo Pereira',
    'Chupa-cu de goianinha',
    'ninguém',
    'esse bot',
    '[CENSURADO]',
    '[UEEEPA]'
]

def main():
    contador('Pessoas', pessoas_comum, pessoas_raro)

if __name__ == '__main__':
    main()
