#Adicionar mais coisas aqui
from Auxiliares.aux_functions import contador

substantivos_comum = [
#Política
    'comunismo',
    'capitalismo',
    'políticos',
    'corrupção',
    'liberalismo',
    'jeitinho brasileiro',
    'bancos',
    'STF',
    'Correios',
    'SUS',
    'Constituição',
    'Urna eletrônica',
    'Economia',
    'Iniciativa privada',
#pop
    'EAD',
    'animes',
    'Vídeo-game',
    'Netflix',
    'TikTok',
    'Twitter',
    'Instagram',
    'Carnaval',
    'Futebol',
#genérico
    'faculdade',
    'escola',
    'livro',
    'cama',
    'filme',
    'computador',
    'celular',
    'arma',
    'música',
    'baderna',
    'protesto',
    'humanidade',
    'traição',
    'relacionamento não-monogâmico',
    'dinheiro',
    'tempestade',
    'cidadão',
    'praia',
#Religião
    'religião',
    'igreja',
    'oração',
    'meditação',
    'Deus',
    'Jesus',
    'Diabo',
    'bíblia',
    'missa de domingo',
    'Buda', #?
    'Miçanga',
#Animais
    'animal',
    'cobra',
    'crocodilo',
    'cachorro',
    'gato',
    'dragão',
    'verme',
    'rato',
#Signos
    'signos',
    'Peixes',
    'Aquário',
    'Sagitário',
    'Ares',
    'Libras',
    'Escorpião',
    'Gêmeos',
    'Câncer',
    'Virgem',
    'Leão',
    'touro',
    'capricornio',
#comida
    'churrasco',
    'carne',
    'comida',
    'sobremesa',
    'fruta',
    'verdura',
    'carboidrato',
    'gordura',
    'chá',
    'salada',
    'leite',
    'queijo',
    'picles',
    'tomate',
    'cuscuz',
    'pudim',
#Drogas
    'drogas',
    'maconha',
    'cigarro',
    'cerveja',
    'cachaça',
    'café',
#Emoções
    'ciúme',
    'depressão',
    'felicidade',
    'amor',
    'paixão',
    'tristeza',
    'saudade',
    'nostalgia',
    'carência',
    'força',
    'fraqueza',
    'beleza',
    'feiura',
#Música
    'Funk proibidão',
    'Samba',
    'Pagode',
    'Rap',
    'Blues',
    'Rock',
    'Reggae',
    'KPop',
    'Festa',
    'Show'
]

substantivos_raro = [
    '2º álbum da Normani',
    'Óleo de macaco',
    'suruba',
    'mitologia grega',
    'filmes da DC',
    'filmes da Marvel',
    'o cu de quem tá lendo',
    'minecraft',
    'pessoa que leva violão para festas',
    'in-senso',
    'purê de batata no cachorro quente',
    'ketchup na pizza',
    'sorvete de menta com chocolate',
    'O JOGO',
    'League of Legends',
    'CS:GO',
    'Free Fire',
    'Viajem no tempo',
    'f1',
    'crack',
    'Python',
    'Java',
    '[CENSURADO]',
    '[Barulho de moto passando]'
]

def main():
    contador('Substantivos', substantivos_comum, substantivos_raro)

if __name__ == '__main__':
    main()